package bacnet

type VendorID uint16

func (vid VendorID) Organization() string {
	return vendorIDOrganization[vid]
}

func (vid VendorID) Contacts() string {
	return vendorIDContacts[vid]
}

func (vid VendorID) Address() string {
	return vendorIDAddress[vid]
}

func (vid VendorID) String() string {
	return vid.Organization() + " -- " + vid.Contacts() + " -- " + vid.Address()
}

var vendorIDOrganization = map[VendorID]string{
	0:    "ASHRAE",
	1:    "NIST",
	2:    "The Trane Company",
	3:    "McQuay International",
	4:    "PolarSoft",
	5:    "Johnson Controls, Inc.",
	6:    "American Auto-Matrix",
	7:    "Siemens Schweiz AG (Formerly: Landis & Staefa Division Europe)",
	8:    "Delta Controls",
	9:    "Siemens Schweiz AG",
	10:   "Schneider Electric",
	11:   "TAC",
	12:   "Orion Analysis Corporation",
	13:   "Teletrol Systems Inc.",
	14:   "Cimetrics Technology",
	15:   "Cornell University",
	16:   "United Technologies Carrier",
	17:   "Honeywell Inc.",
	18:   "Alerton / Honeywell",
	19:   "TAC AB",
	20:   "Hewlett-Packard Company",
	21:   "Dorsette’s Inc.",
	22:   "Siemens Schweiz AG (Formerly: Cerberus AG)",
	23:   "York Controls Group",
	24:   "Automated Logic Corporation",
	25:   "CSI Control Systems International",
	26:   "Phoenix Controls Corporation",
	27:   "Innovex Technologies, Inc.",
	28:   "KMC Controls, Inc.",
	29:   "Xn Technologies, Inc.",
	30:   "Hyundai Information Technology Co., Ltd.",
	31:   "Tokimec Inc.",
	32:   "Simplex",
	33:   "North Building Technologies Limited",
	34:   "Notifier",
	35:   "Reliable Controls Corporation",
	36:   "Tridium Inc.",
	37:   "Sierra Monitor Corporation",
	38:   "Silicon Energy",
	39:   "Kieback & Peter GmbH & Co KG",
	40:   "Anacon Systems, Inc.",
	41:   "Systems Controls & Instruments, LLC",
	42:   "Acuity Brands Lighting, Inc.",
	43:   "Micropower Manufacturing",
	44:   "Matrix Controls",
	45:   "METALAIRE",
	46:   "ESS Engineering",
	47:   "Sphere Systems Pty Ltd.",
	48:   "Walker Technologies Corporation",
	49:   "H I Solutions, Inc.",
	50:   "MBS GmbH",
	51:   "SAMSON AG",
	52:   "Badger Meter Inc.",
	53:   "DAIKIN Industries Ltd.",
	54:   "NARA Controls Inc.",
	55:   "Mammoth Inc.",
	56:   "Liebert Corporation",
	57:   "SEMCO Incorporated",
	58:   "Air Monitor Corporation",
	59:   "TRIATEK, LLC",
	60:   "NexLight",
	61:   "Multistack",
	62:   "TSI Incorporated",
	63:   "Weather-Rite, Inc.",
	64:   "Dunham-Bush",
	65:   "Reliance Electric",
	66:   "LCS Inc.",
	67:   "Regulator Australia PTY Ltd.",
	68:   "Touch-Plate Lighting Controls",
	69:   "Amann GmbH",
	70:   "RLE Technologies",
	71:   "Cardkey Systems",
	72:   "SECOM Co., Ltd.",
	73:   "ABB Gebäudetechnik AG Bereich NetServ",
	74:   "KNX Association cvba",
	75:   "Institute of Electrical Installation Engineers of Japan (IEIEJ)",
	76:   "Nohmi Bosai, Ltd.",
	77:   "Carel S.p.A.",
	78:   "UTC Fire & Security España, S.L.",
	79:   "Hochiki Corporation",
	80:   "Fr. Sauter AG",
	81:   "Matsushita Electric Works, Ltd.",
	82:   "Mitsubishi Electric Corporation, Inazawa Works",
	83:   "Mitsubishi Heavy Industries, Ltd.",
	84:   "Xylem, Inc.",
	85:   "Yamatake Building Systems Co., Ltd.",
	86:   "The Watt Stopper, Inc.",
	87:   "Aichi Tokei Denki Co., Ltd.",
	88:   "Activation Technologies, LLC",
	89:   "Saia-Burgess Controls, Ltd.",
	90:   "Hitachi, Ltd.",
	91:   "Novar Corp./Trend Control Systems Ltd.",
	92:   "Mitsubishi Electric Lighting Corporation",
	93:   "Argus Control Systems, Ltd.",
	94:   "Kyuki Corporation",
	95:   "Richards-Zeta Building Intelligence, Inc.",
	96:   "Scientech R&D, Inc.",
	97:   "VCI Controls, Inc.",
	98:   "Toshiba Corporation",
	99:   "Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works",
	100:  "Custom Mechanical Equipment, LLC",
	101:  "ClimateMaster",
	102:  "ICP Panel-Tec, Inc.",
	103:  "D-Tek Controls",
	104:  "NEC Engineering, Ltd.",
	105:  "PRIVA BV",
	106:  "Meidensha Corporation",
	107:  "JCI Systems Integration Services",
	108:  "Freedom Corporation",
	109:  "Neuberger Gebäudeautomation GmbH",
	110:  "eZi Controls",
	111:  "Leviton Manufacturing",
	112:  "Fujitsu Limited",
	113:  "Vertiv (Formerly Emerson Network Power)",
	114:  "S. A. Armstrong, Ltd.",
	115:  "Visonet AG",
	116:  "M&M Systems, Inc.",
	117:  "Custom Software Engineering",
	118:  "Nittan Company, Limited",
	119:  "Elutions Inc. (Wizcon Systems SAS)",
	120:  "Pacom Systems Pty., Ltd.",
	121:  "Unico, Inc.",
	122:  "Ebtron, Inc.",
	123:  "Scada Engine",
	124:  "Lenze Americas (Formerly: AC Technology Corporation)",
	125:  "Eagle Technology",
	126:  "Data Aire, Inc.",
	127:  "ABB, Inc.",
	128:  "Transbit Sp. z o. o.",
	129:  "Toshiba Carrier Corporation",
	130:  "Shenzhen Junzhi Hi-Tech Co., Ltd.",
	131:  "Tokai Soft",
	132:  "Blue Ridge Technologies",
	133:  "Veris Industries",
	134:  "Centaurus Prime",
	135:  "Sand Network Systems",
	136:  "Regulvar, Inc.",
	137:  "AFDtek Division of Fastek International Inc.",
	138:  "PowerCold Comfort Air Solutions, Inc.",
	139:  "I Controls",
	140:  "Viconics Electronics, Inc.",
	141:  "Yaskawa America, Inc.",
	142:  "DEOS control systems GmbH",
	143:  "Digitale Mess- und Steuersysteme AG",
	144:  "Fujitsu General Limited",
	145:  "Project Engineering S.r.l.",
	146:  "Sanyo Electric Co., Ltd.",
	147:  "Integrated Information Systems, Inc.",
	148:  "Temco Controls, Ltd.",
	149:  "Airtek International Inc.",
	150:  "Advantech Corporation",
	151:  "Titan Products, Ltd.",
	152:  "Regel Partners",
	153:  "National Environmental Product",
	154:  "Unitec Corporation",
	155:  "Kanden Engineering Company",
	156:  "Messner Gebäudetechnik GmbH",
	157:  "Integrated.CH",
	158:  "Price Industries",
	159:  "SE-Elektronic GmbH",
	160:  "Rockwell Automation",
	161:  "Enflex Corp.",
	162:  "ASI Controls",
	163:  "SysMik GmbH Dresden",
	164:  "HSC Regelungstechnik GmbH",
	165:  "Smart Temp Australia Pty. Ltd.",
	166:  "Cooper Controls",
	167:  "Duksan Mecasys Co., Ltd.",
	168:  "Fuji IT Co., Ltd.",
	169:  "Vacon Plc",
	170:  "Leader Controls",
	171:  "Cylon Controls, Ltd.",
	172:  "Compas",
	173:  "Mitsubishi Electric Building Techno-Service Co., Ltd.",
	174:  "Building Control Integrators",
	175:  "ITG Worldwide (M) Sdn Bhd",
	176:  "Lutron Electronics Co., Inc.",
	177:  "Cooper-Atkins Corporation",
	178:  "LOYTEC Electronics GmbH",
	179:  "ProLon",
	180:  "Mega Controls Limited",
	181:  "Micro Control Systems, Inc.",
	182:  "Kiyon, Inc.",
	183:  "Dust Networks",
	184:  "Advanced Building Automation Systems",
	185:  "Hermos AG",
	186:  "CEZIM",
	187:  "Softing",
	188:  "Lynxspring, Inc.",
	189:  "Schneider Toshiba Inverter Europe",
	190:  "Danfoss Drives A/S",
	191:  "Eaton Corporation",
	192:  "Matyca S.A.",
	193:  "Botech AB",
	194:  "Noveo, Inc.",
	195:  "AMEV",
	196:  "Yokogawa Electric Corporation",
	197:  "GFR Gesellschaft für Regelungstechnik",
	198:  "Exact Logic",
	199:  "Mass Electronics Pty Ltd dba Innotech Control Systems Australia",
	200:  "Kandenko Co., Ltd.",
	201:  "DTF, Daten-Technik Fries",
	202:  "Klimasoft, Ltd.",
	203:  "Toshiba Schneider Inverter Corporation",
	204:  "Control Applications, Ltd.",
	205:  "CIMON CO., Ltd.",
	206:  "Onicon Incorporated",
	207:  "Automation Displays, Inc.",
	208:  "Control Solutions, Inc.",
	209:  "Remsdaq Limited",
	210:  "NTT Facilities, Inc.",
	211:  "VIPA GmbH",
	212:  "TSC21 Association of Japan",
	213:  "Strato Automation",
	214:  "HRW Limited",
	215:  "Lighting Control & Design, Inc.",
	216:  "Mercy Electronic and Electrical Industries",
	217:  "Samsung SDS Co., Ltd",
	218:  "Impact Facility Solutions, Inc.",
	219:  "Aircuity",
	220:  "Control Techniques, Ltd.",
	221:  "OpenGeneral Pty., Ltd.",
	222:  "WAGO Kontakttechnik GmbH & Co. KG",
	223:  "Cerus Industrial",
	224:  "Chloride Power Protection Company",
	225:  "Computrols, Inc.",
	226:  "Phoenix Contact GmbH & Co. KG",
	227:  "Grundfos Management A/S",
	228:  "Ridder Drive Systems",
	229:  "Soft Device SDN BHD",
	230:  "Integrated Control Technology Limited",
	231:  "AIRxpert Systems, Inc.",
	232:  "Microtrol Limited",
	233:  "Red Lion Controls",
	234:  "Digital Electronics Corporation",
	235:  "Ennovatis GmbH",
	236:  "Serotonin Software Technologies, Inc.",
	237:  "LS Industrial Systems Co., Ltd.",
	238:  "Square D Company",
	239:  "S Squared Innovations, Inc.",
	240:  "Aricent Ltd.",
	241:  "EtherMetrics, LLC",
	242:  "Industrial Control Communications, Inc.",
	243:  "Paragon Controls, Inc.",
	244:  "A. O. Smith Corporation",
	245:  "Contemporary Control Systems, Inc.",
	246:  "Intesis Software SLU",
	247:  "Ingenieurgesellschaft N. Hartleb mbH",
	248:  "Heat-Timer Corporation",
	249:  "Ingrasys Technology, Inc.",
	250:  "Costerm Building Automation",
	251:  "WILO SE",
	252:  "Embedia Technologies Corp.",
	253:  "Technilog",
	254:  "HR Controls Ltd. & Co. KG",
	255:  "Lennox International, Inc.",
	256:  "RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG",
	257:  "Thermomax, Ltd.",
	258:  "ELCON Electronic Control, Ltd.",
	259:  "Larmia Control AB",
	260:  "BACnet Stack at SourceForge",
	261:  "G4S Security Services A/S",
	262:  "Exor International S.p.A.",
	263:  "Cristal Controles",
	264:  "Regin AB",
	265:  "Dimension Software, Inc.",
	266:  "SynapSense Corporation",
	267:  "Beijing Nantree Electronic Co., Ltd.",
	268:  "Camus Hydronics Ltd.",
	269:  "Kawasaki Heavy Industries, Ltd.",
	270:  "Critical Environment Technologies",
	271:  "ILSHIN IBS Co., Ltd.",
	272:  "ELESTA Energy Control AG",
	273:  "KROPMAN Installatietechniek",
	274:  "Baldor Electric Company",
	275:  "INGA mbH",
	276:  "GE Consumer & Industrial",
	277:  "Functional Devices, Inc.",
	278:  "ESAC",
	279:  "M-System Co., Ltd.",
	280:  "Yokota Co., Ltd.",
	281:  "Hitranse Technology Co., LTD",
	282:  "Vigilent Corporation",
	283:  "Kele, Inc.",
	284:  "Opera Electronics, Inc.",
	285:  "Gentec",
	286:  "Embedded Science Labs, LLC",
	287:  "Parker Hannifin Corporation",
	288:  "MaCaPS International Limited",
	289:  "Link4 Corporation",
	290:  "Romutec Steuer-u. Regelsysteme GmbH",
	291:  "Pribusin, Inc.",
	292:  "Advantage Controls",
	293:  "Critical Room Control",
	294:  "LEGRAND",
	295:  "Tongdy Control Technology Co., Ltd.",
	296:  "ISSARO Integrierte Systemtechnik",
	297:  "Pro-Dev Industries",
	298:  "DRI-STEEM",
	299:  "Creative Electronic GmbH",
	300:  "Swegon AB",
	301:  "Jan Brachacek",
	302:  "Hitachi Appliances, Inc.",
	303:  "Real Time Automation, Inc.",
	304:  "ITEC Hankyu-Hanshin Co.",
	305:  "Cyrus E&M Engineering Co., Ltd.",
	306:  "Badger Meter",
	307:  "Cirrascale Corporation",
	308:  "Elesta GmbH Building Automation",
	309:  "Securiton",
	310:  "OSlsoft, Inc.",
	311:  "Hanazeder Electronic GmbH",
	312:  "Honeywell Security Deutschland, Novar GmbH",
	313:  "Siemens Industry, Inc.",
	314:  "ETM Professional Control GmbH",
	315:  "Meitav-tec, Ltd.",
	316:  "Janitza Electronics GmbH",
	317:  "MKS Nordhausen",
	318:  "De Gier Drive Systems B.V.",
	319:  "Cypress Envirosystems",
	320:  "SMARTron s.r.o.",
	321:  "Verari Systems, Inc.",
	322:  "K-W Electronic Service, Inc.",
	323:  "ALFA-SMART Energy Management",
	324:  "Telkonet, Inc.",
	325:  "Securiton GmbH",
	326:  "Cemtrex, Inc.",
	327:  "Performance Technologies, Inc.",
	328:  "Xtralis (Aust) Pty Ltd",
	329:  "TROX GmbH",
	330:  "Beijing Hysine Technology Co., Ltd",
	331:  "RCK Controls, Inc.",
	332:  "Distech Controls SAS",
	333:  "Novar/Honeywell",
	334:  "The S4 Group, Inc.",
	335:  "Schneider Electric",
	336:  "LHA Systems",
	337:  "GHM engineering Group, Inc.",
	338:  "Cllimalux S.A.",
	339:  "VAISALA Oyj",
	340:  "COMPLEX (Beijing) Technology, Co., LTD.",
	341:  "SCADAmetrics",
	342:  "POWERPEG NSI Limited",
	343:  "BACnet Interoperability Testing Services, Inc.",
	344:  "Teco a.s.",
	345:  "Plexus Technology, Inc.",
	346:  "Energy Focus, Inc.",
	347:  "Powersmiths International Corp.",
	348:  "Nichibei Co., Ltd.",
	349:  "HKC Technology Ltd.",
	350:  "Ovation Networks, Inc.",
	351:  "Setra Systems",
	352:  "AVG Automation",
	353:  "ZXC Ltd.",
	354:  "Byte Sphere",
	355:  "Generiton Co., Ltd.",
	356:  "Holter Regelarmaturen GmbH & Co. KG",
	357:  "Bedford Instruments, LLC",
	358:  "Standair Inc.",
	359:  "WEG Automation - R&D",
	360:  "Prolon Control Systems ApS",
	361:  "Inneasoft",
	362:  "ConneXSoft GmbH",
	363:  "CEAG Notlichtsysteme GmbH",
	364:  "Distech Controls Inc.",
	365:  "Industrial Technology Research Institute",
	366:  "ICONICS, Inc.",
	367:  "IQ Controls s.c.",
	368:  "OJ Electronics A/S",
	369:  "Rolbit Ltd.",
	370:  "Synapsys Solutions Ltd.",
	371:  "ACME Engineering Prod. Ltd.",
	372:  "Zener Electric Pty, Ltd.",
	373:  "Selectronix, Inc.",
	374:  "Gorbet & Banerjee, LLC.",
	375:  "IME",
	376:  "Stephen H. Dawson Computer Service",
	377:  "Accutrol, LLC",
	378:  "Schneider Elektronik GmbH",
	379:  "Alpha-Inno Tec GmbH",
	380:  "ADMMicro, Inc.",
	381:  "Greystone Energy Systems, Inc.",
	382:  "CAP Technologie",
	383:  "KeRo Systems",
	384:  "Domat Control System s.r.o.",
	385:  "Efektronics Pty. Ltd.",
	386:  "Hekatron Vertriebs GmbH",
	387:  "Securiton AG",
	388:  "Carlo Gavazzi Controls SpA",
	389:  "Chipkin Automation Systems",
	390:  "Savant Systems, LLC",
	391:  "Simmtronic Lighting Controls",
	392:  "Abelko Innovation AB",
	393:  "Seresco Technologies Inc.",
	394:  "IT Watchdogs",
	395:  "Automation Assist Japan Corp.",
	396:  "Thermokon Sensortechnik GmbH",
	397:  "EGauge Systems, LLC",
	398:  "Quantum Automation (ASIA) PTE, Ltd.",
	399:  "Toshiba Lighting & Technology Corp.",
	400:  "SPIN Engenharia de Automação Ltda.",
	401:  "Logistics Systems & Software Services India PVT. Ltd.",
	402:  "Delta Controls Integration Products",
	403:  "Focus Media",
	404:  "LUMEnergi Inc.",
	405:  "Kara Systems",
	406:  "RF Code, Inc.",
	407:  "Fatek Automation Corp.",
	408:  "JANDA Software Company, LLC",
	409:  "Open System Solutions Limited",
	410:  "Intelec Systems PTY Ltd.",
	411:  "Ecolodgix, LLC",
	412:  "Douglas Lighting Controls",
	413:  "iSAtech GmbH",
	414:  "AREAL",
	415:  "Beckhoff Automation GmbH",
	416:  "IPAS GmbH",
	417:  "KE2 Therm Solutions",
	418:  "Base2Products",
	419:  "DTL Controls, LLC",
	420:  "INNCOM International, Inc.",
	421:  "BTR Netcom GmbH",
	422:  "Greentrol Automation, Inc",
	423:  "BELIMO Automation AG",
	424:  "Samsung Heavy Industries Co, Ltd",
	425:  "Triacta Power Technologies, Inc.",
	426:  "Globestar Systems",
	427:  "MLB Advanced Media, LP",
	428:  "SWG Stuckmann Wirtschaftliche Gebäudesysteme GmbH",
	429:  "SensorSwitch",
	430:  "Multitek Power Limited",
	431:  "Aquametro AG",
	432:  "LG Electronics Inc.",
	433:  "Electronic Theatre Controls, Inc.",
	434:  "Mitsubishi Electric Corporation Nagoya Works",
	435:  "Delta Electronics, Inc.",
	436:  "Elma Kurtalj, Ltd.",
	437:  "Tyco Fire & Security GmbH",
	438:  "Nedap Security Management",
	439:  "ESC Automation Inc.",
	440:  "DSP4YOU Ltd.",
	441:  "GE Sensing and Inspection Technologies",
	442:  "Embedded Systems SIA",
	443:  "BEFEGA GmbH",
	444:  "Baseline Inc.",
	445:  "M2M Systems Integrators",
	446:  "OEMCtrl",
	447:  "Clarkson Controls Limited",
	448:  "Rogerwell Control System Limited",
	449:  "SCL Elements",
	450:  "Hitachi Ltd.",
	451:  "Newron System SA",
	452:  "BEVECO Gebouwautomatisering BV",
	453:  "Streamside Solutions",
	454:  "Yellowstone Soft",
	455:  "Oztech Intelligent Systems Pty Ltd.",
	456:  "Novelan GmbH",
	457:  "Flexim Americas Corporation",
	458:  "ICP DAS Co., Ltd.",
	459:  "CARMA Industries Inc.",
	460:  "Log-One Ltd.",
	461:  "TECO Electric & Machinery Co., Ltd.",
	462:  "ConnectEx, Inc.",
	463:  "Turbo DDC Südwest",
	464:  "Quatrosense Environmental Ltd.",
	465:  "Fifth Light Technology Ltd.",
	466:  "Scientific Solutions, Ltd.",
	467:  "Controller Area Network Solutions (M) Sdn Bhd",
	468:  "RESOL - Elektronische Regelungen GmbH",
	469:  "RPBUS LLC",
	470:  "BRS Sistemas Eletronicos",
	471:  "WindowMaster A/S",
	472:  "Sunlux Technologies Ltd.",
	473:  "Measurlogic",
	474:  "Frimat GmbH",
	475:  "Spirax Sarco",
	476:  "Luxtron",
	477:  "Raypak Inc",
	478:  "Air Monitor Corporation",
	479:  "Regler Och Webbteknik Sverige (ROWS)",
	480:  "Intelligent Lighting Controls Inc.",
	481:  "Sanyo Electric Industry Co., Ltd",
	482:  "E-Mon Energy Monitoring Products",
	483:  "Digital Control Systems",
	484:  "ATI Airtest Technologies, Inc.",
	485:  "SCS SA",
	486:  "HMS Industrial Networks AB",
	487:  "Shenzhen Universal Intellisys Co Ltd",
	488:  "EK Intellisys Sdn Bhd",
	489:  "SysCom",
	490:  "Firecom, Inc.",
	491:  "ESA Elektroschaltanlagen Grimma GmbH",
	492:  "Kumahira Co Ltd",
	493:  "Hotraco",
	494:  "SABO Elektronik GmbH",
	495:  "Equip'Trans",
	496:  "Temperature Control Specialities Co., Inc (TCS)",
	497:  "FlowCon International A/S",
	498:  "ThyssenKrupp Elevator Americas",
	499:  "Abatement Technologies",
	500:  "Continental Control Systems, LLC",
	501:  "WISAG Automatisierungstechnik GmbH & Co KG",
	502:  "EasyIO",
	503:  "EAP-Electric GmbH",
	504:  "Hardmeier",
	505:  "Mircom Group of Companies",
	506:  "Quest Controls",
	507:  "Mestek, Inc",
	508:  "Pulse Energy",
	509:  "Tachikawa Corporation",
	510:  "University of Nebraska-Lincoln",
	511:  "Redwood Systems",
	512:  "PASStec Industrie-Elektronik GmbH",
	513:  "NgEK, Inc.",
	514:  "t-mac Technologies",
	515:  "Jireh Energy Tech Co., Ltd.",
	516:  "Enlighted Inc.",
	517:  "El-Piast Sp. Z o.o",
	518:  "NetxAutomation Software GmbH",
	519:  "Invertek Drives",
	520:  "Deutschmann Automation GmbH & Co. KG",
	521:  "EMU Electronic AG",
	522:  "Phaedrus Limited",
	523:  "Sigmatek GmbH & Co KG",
	524:  "Marlin Controls",
	525:  "Circutor, SA",
	526:  "UTC Fire & Security",
	527:  "DENT Instruments, Inc.",
	528:  "FHP Manufacturing Company - Bosch Group",
	529:  "GE Intelligent Platforms",
	530:  "Inner Range Pty Ltd",
	531:  "GLAS Energy Technology",
	532:  "MSR-Electronic-GmbH",
	533:  "Energy Control Systems, Inc.",
	534:  "EMT Controls",
	535:  "Daintree Networks Inc.",
	536:  "EURO ICC d.o.o",
	537:  "TE Connectivity Energy",
	538:  "GEZE GmbH",
	539:  "NEC Corporation",
	540:  "Ho Cheung International Company Limited",
	541:  "Sharp Manufacturing Systems Corporation",
	542:  "DOT CONTROLS a.s.",
	543:  "BeaconMedæs",
	544:  "Midea Commercial Aircon",
	545:  "WattMaster Controls",
	546:  "Kamstrup A/S",
	547:  "CA Computer Automation GmbH",
	548:  "Laars Heating Systems Company",
	549:  "Hitachi Systems, Ltd.",
	550:  "Fushan AKE Electronic Engineering Co., Ltd.",
	551:  "Toshiba International Corporation",
	552:  "Starman Systems, LLC",
	553:  "Samsung Techwin Co., Ltd.",
	554:  "ISAS-Integrated Switchgear and Systems P/L",
	555:  "Reserved for ASHRAE",
	556:  "Obvius",
	557:  "Marek Guzik",
	558:  "Vortek Instruments, LLC",
	559:  "Universal Lighting Technologies",
	560:  "Myers Power Products, Inc.",
	561:  "Vector Controls GmbH",
	562:  "Crestron Electronics, Inc.",
	563:  "A&E Controls Limited",
	564:  "Projektomontaza A.D.",
	565:  "Freeaire Refrigeration",
	566:  "Aqua Cooler Pty Limited",
	567:  "Basic Controls",
	568:  "GE Measurement and Control Solutions Advanced Sensors",
	569:  "EQUAL Networks",
	570:  "Millennial Net",
	571:  "APLI Ltd",
	572:  "Electro Industries/GaugeTech",
	573:  "SangMyung University",
	574:  "Coppertree Analytics, Inc.",
	575:  "CoreNetiX GmbH",
	576:  "Acutherm",
	577:  "Dr. Riedel Automatisierungstechnik GmbH",
	578:  "Shina System Co., Ltd",
	579:  "Iqapertus",
	580:  "PSE Technology",
	581:  "BA Systems",
	582:  "BTICINO",
	583:  "Monico, Inc.",
	584:  "iCue",
	585:  "tekmar Control Systems Ltd.",
	586:  "Control Technology Corporation",
	587:  "GFAE GmbH",
	588:  "BeKa Software GmbH",
	589:  "Isoil Industria SpA",
	590:  "Home Systems Consulting SpA",
	591:  "Socomec",
	592:  "Everex Communications, Inc.",
	593:  "Ceiec Electric Technology",
	594:  "Atrila GmbH",
	595:  "WingTechs",
	596:  "Shenzhen Mek Intellisys Pte Ltd.",
	597:  "Nestfield Co., Ltd.",
	598:  "Swissphone Telecom AG",
	599:  "PNTECH JSC",
	600:  "Horner APG, LLC",
	601:  "PVI Industries, LLC",
	602:  "Ela-compil",
	603:  "Pegasus Automation International LLC",
	604:  "Wight Electronic Services Ltd.",
	605:  "Marcom",
	606:  "Exhausto A/S",
	607:  "Dwyer Instruments, Inc.",
	608:  "Link GmbH",
	609:  "Oppermann Regelgerate GmbH",
	610:  "NuAire, Inc.",
	611:  "Nortec Humidity, Inc.",
	612:  "Bigwood Systems, Inc.",
	613:  "Enbala Power Networks",
	614:  "Inter Energy Co., Ltd.",
	615:  "ETC",
	616:  "COMELEC S.A.R.L",
	617:  "Pythia Technologies",
	618:  "TrendPoint Systems, Inc.",
	619:  "AWEX",
	620:  "Eurevia",
	621:  "Kongsberg E-lon AS",
	622:  "FlaktWoods",
	623:  "E + E Elektronik GES M.B.H.",
	624:  "ARC Informatique",
	625:  "SKIDATA AG",
	626:  "WSW Solutions",
	627:  "Trefon Electronic GmbH",
	628:  "Dongseo System",
	629:  "Kanontec Intelligence Technology Co., Ltd.",
	630:  "EVCO S.p.A.",
	631:  "Accuenergy (Canada) Inc.",
	632:  "SoftDEL",
	633:  "Orion Energy Systems, Inc.",
	634:  "Roboticsware",
	635:  "DOMIQ Sp. z o.o.",
	636:  "Solidyne",
	637:  "Elecsys Corporation",
	638:  "Conditionaire International Pty. Limited",
	639:  "Quebec, Inc.",
	640:  "Homerun Holdings",
	641:  "Murata Americas",
	642:  "Comptek",
	643:  "Westco Systems, Inc.",
	644:  "Advancis Software & Services GmbH",
	645:  "Intergrid, LLC",
	646:  "Markerr Controls, Inc.",
	647:  "Toshiba Elevator and Building Systems Corporation",
	648:  "Spectrum Controls, Inc.",
	649:  "Mkservice",
	650:  "Fox Thermal Instruments",
	651:  "SyxthSense Ltd",
	652:  "DUHA System S R.O.",
	653:  "NIBE",
	654:  "Melink Corporation",
	655:  "Fritz-Haber-Institut",
	656:  "MTU Onsite Energy GmbH, Gas Power Systems",
	657:  "Omega Engineering, Inc.",
	658:  "Avelon",
	659:  "Ywire Technologies, Inc.",
	660:  "M.R. Engineering Co., Ltd.",
	661:  "Lochinvar, LLC",
	662:  "Sontay Limited",
	663:  "GRUPA Slawomir Chelminski",
	664:  "Arch Meter Corporation",
	665:  "Senva, Inc.",
	666:  "Reserved for ASHRAE",
	667:  "FM-Tec",
	668:  "Systems Specialists, Inc.",
	669:  "SenseAir",
	670:  "AB IndustrieTechnik Srl",
	671:  "Cortland Research, LLC",
	672:  "MediaView",
	673:  "VDA Elettronica",
	674:  "CSS, Inc.",
	675:  "Tek-Air Systems, Inc.",
	676:  "ICDT",
	677:  "The Armstrong Monitoring Corporation",
	678:  "DIXELL S.r.l",
	679:  "Lead System, Inc.",
	680:  "ISM EuroCenter S.A.",
	681:  "TDIS",
	682:  "Trade FIDES",
	683:  "Knürr GmbH (Emerson Network Power)",
	684:  "Resource Data Management",
	685:  "Abies Technology, Inc.",
	686:  "UAB Komfovent",
	687:  "MIRAE Electrical Mfg. Co., Ltd.",
	688:  "HunterDouglas Architectural Projects Scandinavia ApS",
	689:  "RUNPAQ Group Co., Ltd",
	690:  "Unicard SA",
	691:  "IE Technologies",
	692:  "Ruskin Manufacturing",
	693:  "Calon Associates Limited",
	694:  "Contec Co., Ltd.",
	695:  "iT GmbH",
	696:  "Autani Corporation",
	697:  "Christian Fortin",
	698:  "HDL",
	699:  "IPID Sp. Z.O.O Limited",
	700:  "Fuji Electric Co., Ltd",
	701:  "View, Inc.",
	702:  "Samsung S1 Corporation",
	703:  "New Lift",
	704:  "VRT Systems",
	705:  "Motion Control Engineering, Inc.",
	706:  "Weiss Klimatechnik GmbH",
	707:  "Elkon",
	708:  "Eliwell Controls S.r.l.",
	709:  "Japan Computer Technos Corp",
	710:  "Rational Network ehf",
	711:  "Magnum Energy Solutions, LLC",
	712:  "MelRok",
	713:  "VAE Group",
	714:  "LGCNS",
	715:  "Berghof Automationstechnik GmbH",
	716:  "Quark Communications, Inc.",
	717:  "Sontex",
	718:  "mivune AG",
	719:  "Panduit",
	720:  "Smart Controls, LLC",
	721:  "Compu-Aire, Inc.",
	722:  "Sierra",
	723:  "ProtoSense Technologies",
	724:  "Eltrac Technologies Pvt Ltd",
	725:  "Bektas Invisible Controls GmbH",
	726:  "Entelec",
	727:  "INNEXIV",
	728:  "Covenant",
	729:  "Davitor AB",
	730:  "TongFang Technovator",
	731:  "Building Robotics, Inc.",
	732:  "HSS-MSR UG",
	733:  "FramTack LLC",
	734:  "B. L. Acoustics, Ltd.",
	735:  "Traxxon Rock Drills, Ltd",
	736:  "Franke",
	737:  "Wurm GmbH & Co",
	738:  "AddENERGIE",
	739:  "Mirle Automation Corporation",
	740:  "Ibis Networks",
	741:  "ID-KARTA s.r.o.",
	742:  "Anaren, Inc.",
	743:  "Span, Incorporated",
	744:  "Bosch Thermotechnology Corp",
	745:  "DRC Technology S.A.",
	746:  "Shanghai Energy Building Technology Co, Ltd",
	747:  "Fraport AG",
	748:  "Flowgroup",
	749:  "Skytron Energy, GmbH",
	750:  "ALTEL Wicha, Golda Sp. J.",
	751:  "Drupal",
	752:  "Axiomatic Technology, Ltd",
	753:  "Bohnke + Partner",
	754:  "Function1",
	755:  "Optergy Pty, Ltd",
	756:  "LSI Virticus",
	757:  "Konzeptpark GmbH",
	758:  "Hubbell Building Automation, Inc.",
	759:  "eCurv, Inc.",
	760:  "Agnosys GmbH",
	761:  "Shanghai Sunfull Automation Co., LTD",
	762:  "Kurz Instruments, Inc.",
	763:  "Cias Elettronica S.r.l.",
	764:  "Multiaqua, Inc.",
	765:  "BlueBox",
	766:  "Sensidyne",
	767:  "Viessmann Elektronik GmbH",
	768:  "ADFweb.com srl",
	769:  "Gaylord Industries",
	770:  "Majur Ltd.",
	771:  "Shanghai Huilin Technology Co., Ltd.",
	772:  "Exotronic",
	773:  "SAFECONTROL s.r.o.",
	774:  "Amatis",
	775:  "Universal Electric Corporation",
	776:  "iBACnet",
	777:  "Reserved for ASHRAE",
	778:  "Smartrise Engineering, Inc.",
	779:  "Miratron, Inc.",
	780:  "SmartEdge",
	781:  "Mitsubishi Electric Australia Pty Ltd",
	782:  "Triangle Research International Ptd Ltd",
	783:  "Produal Oy",
	784:  "Milestone Systems A/S",
	785:  "Trustbridge",
	786:  "Feedback Solutions",
	787:  "IES",
	788:  "GE Critical Power",
	789:  "Riptide IO",
	790:  "Messerschmitt Systems AG",
	791:  "Dezem Energy Controlling",
	792:  "MechoSystems",
	793:  "evon GmbH",
	794:  "CS Lab GmbH",
	795:  "8760 Enterprises, Inc.",
	796:  "Touche Controls",
	797:  "Ontrol Teknik Malzeme San. ve Tic. A.S.",
	798:  "Uni Control System Sp. Z o.o.",
	799:  "Weihai Ploumeter Co., Ltd",
	800:  "Elcom International Pvt. Ltd",
	801:  "Philips Lighting",
	802:  "AutomationDirect",
	803:  "Paragon Robotics",
	804:  "SMT System & Modules Technology AG",
	805:  "OS Technology Service and Trading Co., LTD",
	806:  "CMR Controls Ltd",
	807:  "Innovari, Inc.",
	808:  "ABB Control Products",
	809:  "Gesellschaft fur Gebäudeautomation mbH",
	810:  "RODI Systems Corp.",
	811:  "Nextek Power Systems",
	812:  "Creative Lighting",
	813:  "WaterFurnace International",
	814:  "Mercury Security",
	815:  "Hisense (Shandong) Air-Conditioning Co., Ltd.",
	816:  "Layered Solutions, Inc.",
	817:  "Leegood Automatic System, Inc.",
	818:  "Shanghai Restar Technology Co., Ltd.",
	819:  "Reimann Ingenieurbüro",
	820:  "LynTec",
	821:  "HTP",
	822:  "Elkor Technologies, Inc.",
	823:  "Bentrol Pty Ltd",
	824:  "Team-Control Oy",
	825:  "NextDevice, LLC",
	826:  "GLOBAL CONTROL 5 Sp. z o.o.",
	827:  "King I Electronics Co., Ltd",
	828:  "SAMDAV",
	829:  "Next Gen Industries Pvt. Ltd.",
	830:  "Entic LLC",
	831:  "ETAP",
	832:  "Moralle Electronics Limited",
	833:  "Leicom AG",
	834:  "Watts Regulator Company",
	835:  "S.C. Orbtronics S.R.L.",
	836:  "Gaussan Technologies",
	837:  "WEBfactory GmbH",
	838:  "Ocean Controls",
	839:  "Messana Air-Ray Conditioning s.r.l.",
	840:  "Hangzhou BATOWN Technology Co. Ltd.",
	841:  "Reasonable Controls",
	842:  "Servisys, Inc.",
	843:  "halstrup-walcher GmbH",
	844:  "SWG Automation Fuzhou Limited",
	845:  "KSB Aktiengesellschaft",
	846:  "Hybryd Sp. z o.o.",
	847:  "Helvatron AG",
	848:  "Oderon Sp. Z.O.O.",
	849:  "mikolab",
	850:  "Exodraft",
	851:  "Hochhuth GmbH",
	852:  "Integrated System Technologies Ltd.",
	853:  "Shanghai Cellcons Controls Co., Ltd",
	854:  "Emme Controls, LLC",
	855:  "Field Diagnostic Services, Inc.",
	856:  "Ges Teknik A.S.",
	857:  "Global Power Products, Inc.",
	858:  "Option NV",
	859:  "BV-Control AG",
	860:  "Sigren Engineering AG",
	861:  "Shanghai Jaltone Technology Co., Ltd.",
	862:  "MaxLine Solutions Ltd",
	863:  "Kron Instrumentos Elétricos Ltda",
	864:  "Thermo Matrix",
	865:  "Infinite Automation Systems, Inc.",
	866:  "Vantage",
	867:  "Elecon Measurements Pvt Ltd",
	868:  "TBA",
	869:  "Carnes Company",
	870:  "Harman Professional",
	871:  "Nenutec Asia Pacific Pte Ltd",
	872:  "Gia NV",
	873:  "Kepware Tehnologies",
	874:  "Temperature Electronics Ltd",
	875:  "Packet Power",
	876:  "Project Haystack Corporation",
	877:  "DEOS Controls Americas Inc.",
	878:  "Senseware Inc",
	879:  "MST Systemtechnik AG",
	880:  "Lonix Ltd",
	881:  "GMC-I Messtechnik GmbH",
	882:  "Aviosys International Inc.",
	883:  "Efficient Building Automation Corp.",
	884:  "Accutron Instruments Inc.",
	885:  "Vermont Energy Control Systems LLC",
	886:  "DCC Dynamics",
	887:  "Brück Electronic GmbH",
	888:  "Reserved for ASHRAE",
	889:  "NGBS Hungary Ltd.",
	890:  "ILLUM Technology, LLC",
	891:  "Delta Controls Germany Limited",
	892:  "S+T Service & Technique S.A.",
	893:  "SimpleSoft",
	894:  "Candi Controls, Inc.",
	895:  "EZEN Solution Inc.",
	896:  "Fujitec Co. Ltd.",
	897:  "Terralux",
	898:  "Annicom",
	899:  "Bihl+Wiedemann GmbH",
	900:  "Draper, Inc.",
	901:  "Schüco International KG",
	902:  "Otis Elevator Company",
	903:  "Fidelix Oy",
	904:  "RAM GmbH Mess- und Regeltechnik",
	905:  "WEMS",
	906:  "Ravel Electronics Pvt Ltd",
	907:  "OmniMagni",
	908:  "Echelon",
	909:  "Intellimeter Canada, Inc.",
	910:  "Bithouse Oy",
	911:  "Reserved for ASHRAE",
	912:  "BuildPulse",
	913:  "Shenzhen 1000 Building Automation Co. Ltd",
	914:  "AED Engineering GmbH",
	915:  "Güntner GmbH & Co. KG",
	916:  "KNXlogic",
	917:  "CIM Environmental Group",
	918:  "Flow Control",
	919:  "Lumen Cache, Inc.",
	920:  "Ecosystem",
	921:  "Potter Electric Signal Company, LLC",
	922:  "Tyco Fire & Security S.p.A.",
	923:  "Watanabe Electric Industry Co., Ltd.",
	924:  "Causam Energy",
	925:  "W-tec AG",
	926:  "IMI Hydronic Engineering International SA",
	927:  "ARIGO Software",
	928:  "MSA Safety",
	929:  "Smart Solucoes Ltda - MERCATO",
	930:  "PIATRA Engineering",
	931:  "ODIN Automation Systems, LLC",
	932:  "Belparts NV",
	933:  "UAB, SALDA",
	934:  "Alre-IT Regeltechnik GmbH",
	935:  "Ingenieurbüro H. Lertes GmbH & Co. KG",
	936:  "Breathing Buildings",
	937:  "eWON SA",
	938:  "Cav. Uff. Giacomo Cimberio S.p.A",
	939:  "PKE Electronics AG",
	940:  "Allen",
	941:  "Kastle Systems",
	942:  "Logical Electro-Mechanical (EM) Systems, Inc.",
	943:  "ppKinetics Instruments, LLC",
	944:  "Cathexis Technologies",
	945:  "Sylop sp. Z o.o. sp.k",
	946:  "Brauns Control GmbH",
	947:  "Omron Corporation",
	948:  "Wildeboer Bauteile Gmbh",
	949:  "Shanghai Biens Technologies Ltd",
	950:  "Beijing HZHY Technology Co., Ltd",
	951:  "Building Clouds",
	952:  "The University of Sheffield-Department of Electronic and Electrical Engineering",
	953:  "Fabtronics Australia Pty Ltd",
	954:  "SLAT",
	955:  "Software Motor Corporation",
	956:  "Armstrong International Inc.",
	957:  "Steril-Aire, Inc.",
	958:  "Infinique",
	959:  "Arcom",
	960:  "Argo Performance, Ltd",
	961:  "Dialight",
	962:  "Ideal Technical Solutions",
	963:  "Neurobat AG",
	964:  "Neyer Software Consulting LLC",
	965:  "SCADA Technology Development Co., Ltd.",
	966:  "Demand Logic Limited",
	967:  "GWA Group Limited",
	968:  "Occitaline",
	969:  "NAO Digital Co., Ltd.",
	970:  "Shenzhen Chanslink Network Technology Co., Ltd.",
	971:  "Samsung Electronics Co., Ltd.",
	972:  "Mesa Laboratories, Inc.",
	973:  "Fischer",
	974:  "OpSys Solutions Ltd.",
	975:  "Advanced Devices Limited",
	976:  "Condair",
	977:  "INELCOM Ingenieria Electronica Comercial S.A.",
	978:  "GridPoint, Inc.",
	979:  "ADF Technologies Sdn Bhd",
	980:  "EPM, Inc.",
	981:  "Lighting Controls Ltd",
	982:  "Perix Controls Ltd.",
	983:  "AERCO International, Inc.",
	984:  "KONE Inc.",
	985:  "Ziehl-Abegg SE",
	986:  "Robot, S.A.",
	987:  "Optigo Networks, Inc.",
	988:  "Openmotics BVBA",
	989:  "Metropolitan Industries, Inc.",
	990:  "Huawei Technologies Co., Ltd.",
	991:  "OSRAM Sylvania, Inc.",
	992:  "Vanti",
	993:  "Cree, Inc.",
	994:  "Richmond Heights SDN BHD",
	995:  "Payne-Sparkman Lighting Mangement",
	996:  "Ashcroft",
	997:  "Jet Controls Corp",
	998:  "Zumtobel Lighting GmbH",
	999:  "Reserved for ASHRAE",
	1000: "Ekon GmbH",
	1001: "Molex",
	1002: "Maco Lighting Pty Ltd.",
	1003: "Axecon Corp.",
	1004: "Tensor plc",
	1005: "Kaseman Environmental Control Equipment (Shanghai) Limited",
	1006: "AB Axis Industries",
	1007: "Netix Controls",
	1008: "Eldridge Products, Inc.",
	1009: "Micronics",
	1010: "Fortecho Solutions Ltd",
	1011: "Sellers Manufacturing Company",
	1012: "Rite-Hite Doors, Inc.",
	1013: "Violet Defense LLC",
	1014: "Simna",
	1015: "Multi-Énergie Best Inc.",
	1016: "Mega System Technologies, Inc.",
	1017: "Rheem",
	1018: "Ing. Punzenberger COPA-DATA GmbH",
	1019: "MEC Electronics GmbH",
	1020: "Taco Comfort Solutions",
	1021: "Alexander Maier GmbH",
	1022: "Ecorithm, Inc.",
	1023: "Accurro Ltd",
	1024: "ROMTECK Australia Pty Ltd",
	1025: "Splash Monitoring Limited",
	1026: "Light Application",
	1027: "Logical Building Automation",
	1028: "Exilight Oy",
	1029: "Hager Electro SAS",
	1030: "KLIF Co., LTD",
	1031: "HygroMatik",
	1032: "Daniel Mousseau Programmation & Electronique",
	1033: "Aerionics Inc.",
	1034: "M2S Electronique Ltee",
	1035: "Automation Components, Inc.",
	1036: "Niobrara Research & Development Corporation",
	1037: "Netcom Sicherheitstechnik GmbH",
	1038: "Lumel S.A.",
	1039: "Great Plains Industries, Inc.",
	1040: "Domotica Labs S.R.L",
	1041: "Energy Cloud, Inc.",
	1042: "Vomatec",
	1043: "Demma Companies",
	1044: "Valsena",
	1045: "Comsys Bärtsch AG",
	1046: "bGrid",
	1047: "MDJ Software Pty Ltd",
	1048: "Dimonoff, Inc.",
	1049: "Edomo Systems, GmbH",
	1050: "Effektiv, LLC",
	1051: "SteamOVap",
	1052: "grandcentrix GmbH",
	1053: "Weintek Labs, Inc.",
	1054: "Intefox GmbH",
	1055: "Radius22 Automation Company",
	1056: "Ringdale, Inc.",
	1057: "Iwaki America",
	1058: "Bractlet",
	1059: "STULZ Air Technology Systems, Inc.",
	1060: "Climate Ready Engineering",
	1061: "Genea Energy Partners",
	1062: "IoTall Chile",
	1063: "IKS Co., Ltd.",
	1064: "Yodiwo AB",
	1065: "TITAN electronic GmbH",
	1066: "IDEC Corporation",
	1067: "SIFRI SL",
	1068: "Thermal Gas Systems Inc.",
	1069: "Building Automation Products, Inc.",
	1070: "Asset Mapping",
	1071: "Smarteh Company",
	1072: "Datapod Australia Pty Ltd.",
	1073: "Buildings Alive Pty Ltd",
	1074: "Digital Elektronik",
	1075: "Talent Automação e Tecnologia Ltda",
	1076: "Norposh Limited",
	1077: "Merkur Funksysteme AG",
	1078: "Faster CZ spol. S.r.o",
	1079: "Eco-Adapt",
	1080: "Energocentrum Plus, s.r.o",
	1081: "amBX UK Ltd",
	1082: "Western Reserve Controls, Inc.",
	1083: "LayerZero Power Systems, Inc.",
	1084: "CIC Jan Hřebec s.r.o.",
	1085: "Sigrov BV",
	1086: "ISYS-Intelligent Systems",
	1087: "Gas Detection (Australia) Pty Ltd",
	1088: "Kinco Automation (Shanghai) Ltd.",
	1089: "Lars Energy, LLC",
	1090: "Flamefast (UK) Ltd.",
	1091: "Royal Service Air Conditioning",
	1092: "Ampio Sp. Z o.o.",
	1093: "Inovonics Wireless Corporation",
	1094: "Nvent Thermal Management",
	1095: "Sinowell Control System Ltd",
	1096: "Moxa Inc.",
	1097: "Matrix iControl SDN BHD",
	1098: "PurpleSwift",
	1099: "OTIM Technologies",
	1100: "FlowMate Limited",
	1101: "Degree Controls, Inc.",
	1102: "Fei Xing (Shanghai) Software Technologies Co., Ltd.",
	1103: "Berg GmbH",
}

var vendorIDContacts = map[VendorID]string{
	0:    "Stephanie Reiniche, MOS",
	1:    "Steven T. Bushby",
	2:    "Sharon Dinges",
	3:    "Dan Halvorson, Controls Product Manager",
	4:    "David M. Fisher",
	5:    "John Ruiz",
	6:    "Will Kay, Operations Director",
	7:    "Klaus Wächter, Global Standardization Manager",
	8:    "Carl Neilson",
	9:    "Klaus Wächter, Global Standardization Manager",
	10:   "Kevin Sweeney, Manager, Controller Software",
	11:   "Kevin Strohman, Commercial Technology",
	12:   "Wayne Werner",
	13:   "Richard Desmarais, Dir. of Engineering",
	14:   "Jim Butler",
	15:   "H. Michael Newman",
	16:   "Mark Jones",
	17:   "Anil Saigal",
	18:   "Bill Swan, Engineering Fellow",
	19:   "Christer Scheja, Product Manager Communication",
	20:   "Jim Rounds, R&D Functional Manager",
	21:   "Fred A. Trivette, Jr., Operations Manager",
	22:   "Klaus Wächter, Global Standardization Manager",
	23:   "Roger Woodward, Director of Controls",
	24:   "Mike Danner, Software Engineer",
	25:   "Dick Cress",
	26:   "Christopher Martin, Sr. Manager—Product Marketing",
	27:   "Bruce D. Arnold, V.P., Engineering",
	28:   "Wayne D. Kehler",
	29:   "Alan Hale, President",
	30:   "Kang Myung Ung, Research Director",
	31:   "Kiyoshi Fujii, Senior Executive DIrector",
	32:   "Charles Winterble, Vice President Product Development",
	33:   "James Palmer, Business Development",
	34:   "Michael J. Lynch, Director of Business Development",
	35:   "Thomas Zaban, P.E., VP Marketing",
	36:   "Danny Wahlquist, VP",
	37:   "Richard Theron, Product Manager",
	38:   "Mike Hadley, VP Marketing",
	39:   "Hans Symanczik",
	40:   "Bala Padmakumar, Pres. & CEO",
	41:   "H. Nelson Bender, VP Marketing/Sales",
	42:   "Rich Westrick, VP of Network Controls Engineering",
	43:   "Derek Rowbotham, Tech. Director",
	44:   "Dana K. Wallace, Controls Special Project Manager",
	45:   "David John, Director of Marketing",
	46:   "Cherisse Nicastro, Project Manager",
	47:   "Dr. Peter Hammer",
	48:   "Al Walker, President",
	49:   "Rod Hampton, VP Engineering",
	50:   "Martin Brust-Theiss, Company Leader",
	51:   "Peter Opl",
	52:   "Craig V. Warne, Manager Electrical Engr. (Tulsa)",
	53:   "Tohru Hirano, General Manager",
	54:   "Jai-Woo Lee, General of R&D",
	55:   "Arthur Borland, Control Systems Product Manager",
	56:   "Steven Ziejewski, Operations Manager",
	57:   "Richard Mitchell, Engineering Manager",
	58:   "Paresh Dave, Manager, Applications Engineering",
	59:   "James E. Hall, CEO",
	60:   "Eric Peterschmidt, VP of Sales",
	61:   "Greg Michek",
	62:   "James Doubles, CEO",
	63:   "Keith Kelly, President & CEO",
	64:   "Robert Kniss, Electrical Engineering Manager",
	65:   "Kevin Fedor, VTAC 7 Drives Marketing Engineer",
	66:   "Richard C. White, VP",
	67:   "Neil Kenny, Managing Director",
	68:   "Doug Ford, President",
	69:   "Panjoerg Salzmann, Sales Manager",
	70:   "Donald A. Raymond, President/CEO",
	71:   "Steve Platt, Principal Engineer",
	72:   "Kazuhiko Tsushima, Director",
	73:   "Georg Setzer, Mgr. Building Automation Control Centers",
	74:   "Heinz Lux, Director",
	75:   "Soji Ishiyama, Secretary General",
	76:   "Yukimasa Tachibana, Tech. Department Manager",
	77:   "Simone Ravazzolo, Product Manager",
	78:   "Charl du Plessis",
	79:   "Naoya Matsuoka, Manager",
	80:   "Roland Hofstetter, Product Management, Head of Automation Station and System Integration",
	81:   "Keiji Haga, Director",
	82:   "Hiroshi Yoshikawa, Manager, Bldg. Systems Section",
	83:   "Chuzo Ninagawa, Manager",
	84:   "James Gu, Controls and Instrumentation Supervisor",
	85:   "Hiroshi Ito, Director of Product Development Department",
	86:   "Doug Paton, Product Line Manager",
	87:   "Nobuyasu Murase, System Department Manager, System Division",
	88:   "Steven Fey",
	89:   "Joachim Krusch, Head of Technical Marketing Group Europe",
	90:   "Nobuhisa Kobayashi, Manager of Building Systems Engineering Dept.",
	91:   "Alan Carter, Head of New Product Development",
	92:   "Kiyoshi Nakamura, Manager, System Lighting Technical Section",
	93:   "David Flood, Manager, Research & Development",
	94:   "Hiroshi Okada, Dep. Mgr., Marketing & Engineering Division",
	95:   "Edmund B. Richards, Owner",
	96:   "Jean-Pierre Drolet, Ph.D., Director, Software R&D",
	97:   "Bruce M. Dolan, Marketing Manager",
	98:   "Kazumasa Uchida, Mgr. of Building Systems Solution Group",
	99:   "Masami Iwahashi, System Control Section",
	100:  "Dick Peitz, President",
	101:  "Dennis Meyer, Product Manager",
	102:  "Lane Ingram, CEO",
	103:  "Ed Veldman, CEO",
	104:  "Hideo Takahashi, Senior Manager",
	105:  "Marco Polet, Project Manager R&D Software",
	106:  "Akinobu Kobayashi, Gen'l Mgr. of Public Facilities Engineering Division",
	107:  "Tim Gooch, Project Manager",
	108:  "Toshi Uehara, Manager",
	109:  "Klaus Lenkner, Company Leader",
	110:  "Craig Potter, Engineering Manager",
	111:  "Robert Hick, VP Research & Development",
	112:  "Munetsugu Takauchi, Public Network Solution Dept. Director",
	113:  "Darryl Brown, Product Manager",
	114:  "Gaby Haddad, Product Development Specialist",
	115:  "Norbert Kraus, Software Development",
	116:  "Paul A. Valentine",
	117:  "Ronald Davis, Owner",
	118:  "Minori Miyagawa, General Manager, Sales Eng. Dept.",
	119:  "Emmanuel Vitrac, Director of Marketing, Europe & Asia",
	120:  "Scott Finneran",
	121:  "Harry Schulz, Sr. Development Engineer",
	122:  "Michael J. Urbaniak, Senior Vice-President",
	123:  "Chris Gurtler, President",
	124:  "Michael Mamro, Engineering Manager SW & Controls",
	125:  "Harshad Shah, President",
	126:  "Minh Tran, Senior Controls Engineer",
	127:  "Tim Skell, Lead Application Engineer",
	128:  "Frank Wlodzimierz, President",
	129:  "Ichiro Honda, Gen'l Mgr, System Solution Engineering Development Group",
	130:  "Zhengyuan Xu, General Manager",
	131:  "Matsura Akira",
	132:  "Ron Poskevich, General Manager",
	133:  "Marc Bowman, VP Engineering",
	134:  "Robert D. Caldwell, President",
	135:  "Hans J. Lau, President",
	136:  "Eric Boisclair, Analyst",
	137:  "Ashraf Ali, P. Eng. President",
	138:  "Curt Musser, VP of PowerCold Energy Systems",
	139:  "Hyun Jeong, Vice President",
	140:  "David Durian, Engineering Manager",
	141:  "Ron Fox, Senior Development Engineer",
	142:  "Martin Beckmann, Sales Director",
	143:  "Volker Wucher, Software Development",
	144:  "Naoki Kawaguchi, Manager of ACEE Division",
	145:  "David Ricci",
	146:  "Sachiyoshi Ukai, Manager",
	147:  "Dan Bellows, CEO",
	148:  "Maurice Duteau, Manager Director",
	149:  "Bill Chao, President",
	150:  "Michael Rothwell, Director, Marketing & eAutomation Engineering Center",
	151:  "Iain Twiss, Technical Manager",
	152:  "Arien Peterse, Manager",
	153:  "Christian Renaud, Design Engineer",
	154:  "Shogo Nasu, CEO",
	155:  "Masayuki Tsuji, General Manager, System Solution Dept.",
	156:  "Volker Barufke",
	157:  "Stephen Wreford-Doree",
	158:  "Mike Nicholson, Electronic Development Center Manager",
	159:  "Hermann Lippert",
	160:  "Scott D. Braun, Manager, Communications Products, Drives Business",
	161:  "Karl T. C. Swanson, Operations",
	162:  "Mashuri L. Warren, Director of Product Development",
	163:  "Gert-Ulrich Vack, General Manager",
	164:  "Ulrich Pink",
	165:  "Peter Symons, Director",
	166:  "David Viveiros, Product Manager",
	167:  "Jihyung Kim, Chief Technology Officer",
	168:  "Kazutaka Kohata, Staff Manager",
	169:  "Jani Smeds, Development Engineer",
	170:  "Lin Xing Yuan, General Manager",
	171:  "Malachy Lynch, Firmware Engineer",
	172:  "Lesnek Skreta, Technical Director",
	173:  "Hiroyasu Tabata, Assistant Manager",
	174:  "Jonathan P. Fulton, President",
	175:  "Chan Weng Tong, Senior Manager",
	176:  "Scott Ziegenfus, Senior Applications Engineer",
	177:  "John Greene, Director of Technology Development",
	178:  "Dietmar Loy",
	179:  "Marc Bergeron",
	180:  "Eric Ho, General Manager",
	181:  "Brian Walterick, President",
	182:  "James B. Rimmer, Member of Technical Staff",
	183:  "Pedro Rump, VP Engineering",
	184:  "Bryan Grayson, R&D Manager",
	185:  "Andreas Heisel, Manager of Software Development",
	186:  "Piotr Golabek, Product Manager",
	187:  "Achim Liebl, Head of Development",
	188:  "Shawn Jocobson, Director of Application Development",
	189:  "Jean-Pierre Guilmeau, Vice-President Marketing",
	190:  "Ove Wiuff, Product Manager",
	191:  "Mark Verheyen, Principal Engineer",
	192:  "Juan Leni, Director Engineering",
	193:  "Henrik Johansson",
	194:  "Jean-Pierre Dionne, President",
	195:  "Bernhard Hall, AMEV - Geschäftsstelle",
	196:  "Hiroaki Tanaka, Senior Engineer",
	197:  "Volker Westerheide, Managing Director",
	198:  "Matthew Barlage, Product Development Engineer",
	199:  "Stephen A. Miranda, Managing Director",
	200:  "Makoto Kojima, Deputy General Manager of Engineering Department",
	201:  "Wolfgang Fries",
	202:  "Ivan Svancara, Director",
	203:  "Hiromichi Nishimura, Senior Specialist",
	204:  "Doron Matatyahu, Development Manager",
	205:  "Jae-hwan Lee",
	206:  "David B. Johnston, Product Manager",
	207:  "Robert P. Lowry, Electrical Engineer",
	208:  "James G. Hogenson, President",
	209:  "Martyn J. Taylor, Technical Director",
	210:  "Kazuo Oshima, Executive Manager",
	211:  "Markus Krauss",
	212:  "Ryuji Yanagihara, Manager",
	213:  "Andre Baril, President",
	214:  "Greg Keall, Managing Director",
	215:  "David J. Long, Software Engineer",
	216:  "John D. Maniraj, CEO",
	217:  "Woon-Hak Paek, General Manager of IBS Development Division",
	218:  "Keith E. Gipson, CTO",
	219:  "Scott Sitterly, Systems Integration Manager",
	220:  "Stephen Turner, Development Engineer",
	221:  "William Oldjohn, Managing Director",
	222:  "Thomas Albers, Technical Director Electronics",
	223:  "Kent Holce, CEO",
	224:  "Doug Griffin, Lead Software Engineer",
	225:  "Drew Mire, Vice President of Operations",
	226:  "Thomas Erben",
	227:  "Henrik Frederiksen, Product Manager Data Communication",
	228:  "Paul Oudraad, Manager R & D",
	229:  "Pang Wai Yeen",
	230:  "Hayden Burr, Director",
	231:  "Stephen A. Wallis, President",
	232:  "Mike Baker, Director",
	233:  "Mike Granby, President",
	234:  "Yoshiyuki Murata, General Manager",
	235:  "Hartmut Freihofer, Director",
	236:  "Matthew Lohbihler, President",
	237:  "Kiyeon Kim",
	238:  "Drew Reid, Product Manager, Lighting Control Business",
	239:  "Sam Saprunoff, President",
	240:  "Bhuvnesh Sharma, Business Director - Devices Group",
	241:  "Kenneth Barclay, President",
	242:  "Darrin Hansen, President",
	243:  "Larry Winterbourne, Vice President",
	244:  "Tom Van Sistine, Principal Engineer",
	245:  "Bennet Levine, R&D Manager",
	246:  "Josep Ceron, General Manager",
	247:  "Norbert Hartleb",
	248:  "Dan Shprecher, Chief Engineer",
	249:  "Watson Wu, Senior Specialist",
	250:  "David E. Matthews, Sales & Marketing Manager",
	251:  "Stephan Greitzke, Head of Engineering",
	252:  "Andrew Chu, Chief Technology Officer",
	253:  "Patrick Goddefroy, Sales and Marketing Manager",
	254:  "Roul Placzek, Director",
	255:  "Krishna Doddamane, Senior Staff Engineer",
	256:  "Reiner Dunwald",
	257:  "Patrick Davis, R&D Manager",
	258:  "Tibor Erdelyi, General Manager",
	259:  "Hans Bolov, President",
	260:  "Steve Karg, Developer",
	261:  "Knud Danielsen, Product Manager",
	262:  "Claudio Urbani, Product Manager HMI",
	263:  "Martin Labbe, R&D Manager",
	264:  "Urban Fosseus, Senior Software Designer",
	265:  "Shawn Overcash, President",
	266:  "Kurt Sowa, Director of Software Engineering",
	267:  "Goober Zhou, R&D Manager",
	268:  "David Procunier, Assistant Engineer",
	269:  "Mutsuji Sakai, Manager of Electrical & Control Eng. Section",
	270:  "Laura Donahue, Purchasing Agent",
	271:  "Young Kwak, Manager, Applications Engineering",
	272:  "Angelo Quadroni, General Manager",
	273:  "Ir. J.A.J. (Joep) van der Velden, Landelijk Manager Meet- en Regeltechniek",
	274:  "Michael S. Thomas, Design Engineer, Control Systems",
	275:  "Florian Kienast, Manager for SCADA Systems / Dipl.-Ing.",
	276:  "Paul E. Bunnell, Product Manager-Standard Drives and Soft Starts",
	277:  "Kenneth W. Rittmann, President",
	278:  "Salvatore Cataldi, Technical Manager",
	279:  "Koichi Yoshimura, Assistant Manager, R&D Department",
	280:  "Masato Kuwana, Assistant Manager, Shiga Factory",
	281:  "Zhao Gaozuo, General Manager",
	282:  "Cliff Federspiel",
	283:  "Lisa Kisil-Dense, Electrical Products Business Unit Manager",
	284:  "Keith Rasmussen, President",
	285:  "Marcel Landry, VP Division RVD",
	286:  "David A. Bruno, CTO",
	287:  "Steven Schnelle, Engineering Manager, Climate Systems Division",
	288:  "L.M. Cheng, CEO",
	289:  "Yen Pham, President",
	290:  "Stefan Kister, Quality Manager",
	291:  "Michael Gerstweiler, Vice President",
	292:  "Chris Liebig, System Administrator",
	293:  "Sam Sidhom",
	294:  "Jean-Luc Citerne, Services & Integrated Sys. Team Mgr.",
	295:  "Xiaoyan Xi, Marketing Manager",
	296:  "Maik Sauerlaender, Technical Engineer",
	297:  "Peter Hertrick, Systems Development Engineer",
	298:  "Jennifer Schroer, Program Manager",
	299:  "Reiner H. Schmahl, CEO",
	300:  "Mattias Hedfjard, Development Engineer, Electrical Components",
	301:  "Jan Brachacek, Owner",
	302:  "Keiji Sato, Chief Engineer",
	303:  "Jeff Stiefvater, VP Operations",
	304:  "Hiroaki Aoyama, Manager, Computer System Dept.",
	305:  "Cedric Lee, Exporting Manager",
	306:  "William Roeber, Principal Managing Engineer",
	307:  "Victor Tung, VP, Engineering",
	308:  "Urs Beck, Managing Director",
	309:  "Horst Geiser, Product Development Manager",
	310:  "Jon H. Peterson, Vice President of Engineering",
	311:  "Erwin Hanazeder, General Manager",
	312:  "Andrea Bergerhoff, Managing Director",
	313:  "Ken Rempe, P.E., Energy Management Division",
	314:  "Klaus Jandl, Head of Technology",
	315:  "Elan Roy, R&D & Engineering Manager",
	316:  "Markus Janitza, Director",
	317:  "Maik John, Owner",
	318:  "Gerard A. Buter, Manager R&D",
	319:  "Ramesh Songukrishnasamy, VP/GM Building Solutions",
	320:  "Sergey Ziskovich, General Manager",
	321:  "Jennifer H. Skjellum, Vice President, Software Solutions",
	322:  "Jeffrey D. Cox, Manager, Operations & Customer Service",
	323:  "Alex Kugel, Hardware Development Manager",
	324:  "Eva C. Wang, Director, Software Development",
	325:  "Horst Geiser, Product Development Manager",
	326:  "Saagar Govil, Sales & Marketing Manager",
	327:  "John J. Grana, Sr. VP and GM, Embedded Systems Group",
	328:  "John Minack, Development Engineer",
	329:  "Friedrich Sikosek, Product Management Systems",
	330:  "Xiaoyong Zhao, Manager",
	331:  "James F Ring, President",
	332:  "Maxime Ormancey, Quality Manager",
	333:  "John Weisenberger, Product Manager",
	334:  "Steve E. Jones, President",
	335:  "Ronald H. Naismith, Sr. Principal Technical Specialist",
	336:  "Christo Malan, Development Engineer",
	337:  "Gordon Maretzki, President",
	338:  "Paul Meyer, Technical Manager",
	339:  "Matti Kokki, Chief Engineer",
	340:  "Sally Li, Sales Manager",
	341:  "Jim Mimlitz, President",
	342:  "Ringo Lee, Director",
	343:  "Edward Hague, President",
	344:  "Jaromir Klaban, Member of the Board",
	345:  "James Leaper, CEO",
	346:  "Keith Kazenski, Electrical Engineer",
	347:  "Philip J. A. Ling, Vice President - Technology",
	348:  "Akira Nakashima, Director of Product Development",
	349:  "Martin Ip, Project Director",
	350:  "John Schnipkoweit, Chief Technology Officer",
	351:  "Anthony Batista, Project Engineering Manager",
	352:  "Raj Tiwari, Vice President & CTO",
	353:  "David Barrett, Director",
	354:  "Nicholas Saparoff, President",
	355:  "Jefferson Liu, General Manager",
	356:  "Ralf Schulze, Managing Director",
	357:  "Adam Smola, Manager",
	358:  "Pierre Longval, Vice President",
	359:  "Alexandre José da Silva, Software Design",
	360:  "Thomas Maltesen, Managing Director",
	361:  "Sebastien Cand, General Manager",
	362:  "Peter Vontluck, Project Manager",
	363:  "Jurgen Prasuhn, Technical Director, Cooper Safety",
	364:  "Charles Gauvin, Vice President - R&D",
	365:  "Min-Hsien Chien, Engineer",
	366:  "David M. Oravetz, VP of Engineering",
	367:  "Piotr Fedyk, Director",
	368:  "Jens Antonsen, Product Manager HVAC",
	369:  "Zeev I Horovitz, Director R&D",
	370:  "Andy Devine, Technical Director",
	371:  "Leon Karanfil, Product Manager",
	372:  "Ron Jackson, Managing Director",
	373:  "Jerauld T. Numata, President",
	374:  "Matt Gorbet, Managing Partner",
	375:  "Ildebrando Vignati, R & S Manager",
	376:  "Stephen Dawson",
	377:  "Fred George",
	378:  "Bernd Drost",
	379:  "Jürgen Eschenbacher",
	380:  "Crystal DePuy",
	381:  "Lucas Steeves",
	382:  "Patrice Chateau",
	383:  "Kenn Roland",
	384:  "Jan Vidim",
	385:  "Philip Scott",
	386:  "Christian Wenzl",
	387:  "Christian Uehlinger",
	388:  "Fabio Facchin",
	389:  "Peter Chipkin",
	390:  "Bruce Myers",
	391:  "Ian Moir-Porteous",
	392:  "Anders Lindgren",
	393:  "David Lucas",
	394:  "Charlie Mayne",
	395:  "Yukiko Futatsugi",
	396:  "Jorg Teichmann",
	397:  "David Mosberger",
	398:  "Roberto De Jesus",
	399:  "Yasushi Morimoto",
	400:  "Luis Closs",
	401:  "Ajay Nirantar",
	402:  "Carl Neilson",
	403:  "Andrey Tsylev",
	404:  "Timothy Parry",
	405:  "Mr. Emanuel Galea",
	406:  "Martin Stich",
	407:  "Raymond Hong, President",
	408:  "Coleman Brumley, President",
	409:  "Steve Brown",
	410:  "Shane Carlyon",
	411:  "Woody Boyd",
	412:  "George Capelo",
	413:  "André Kraski",
	414:  "Julien Bennet",
	415:  "Ralf Vienken",
	416:  "Olaf Russak",
	417:  "Steve Roberts",
	418:  "John Novak",
	419:  "Sue Sackett",
	420:  "Philipp Roosli",
	421:  "Franz Albicker",
	422:  "Chris Mezenski",
	423:  "Peter Schmidlin",
	424:  "Tae-Kyung Chung",
	425:  "David Perry",
	426:  "Jason Wilson",
	427:  "Joseph Inzerillo",
	428:  "Sascha Stuckmann",
	429:  "Stacy Meszaros",
	430:  "Chris Scanlan",
	431:  "Andreas Lestin",
	432:  "Haejin Kim",
	433:  "Troy Hatley",
	434:  "Yoshihiro Nagataki",
	435:  "Tai-Tsung Huang",
	436:  "Ninoslav Kurtalj",
	437:  "Faruk Meah, Senior Manager R&D",
	438:  "Albert Dercksen",
	439:  "Jim Spronsen",
	440:  "Antoine Rouget",
	441:  "Christopher Frail",
	442:  "Edgars Klavinskis",
	443:  "Manfred Kraußer",
	444:  "Tim Hickenlooper",
	445:  "William Harrison",
	446:  "Michael Wilson",
	447:  "Glenn Smith",
	448:  "Roger Song",
	449:  "Hami Chanon",
	450:  "Koichi Koyano, Senior Engineer",
	451:  "Serge Le Men, Manager-Board Member",
	452:  "L.C. Segaar",
	453:  "William Russell",
	454:  "Hermann Betz",
	455:  "Bob Gulliver",
	456:  "Stefan Reis",
	457:  "Peter Chirivas",
	458:  "Anold Chao",
	459:  "Rick Williams",
	460:  "Hugues de Milleville",
	461:  "Steven Yang",
	462:  "Karl Kaiser",
	463:  "Roland Quenzer",
	464:  "Xiangyang Zheng",
	465:  "Sashi Bala",
	466:  "Randall Logan",
	467:  "K.H. Tang",
	468:  "Sascha Kunze",
	469:  "Paul Hennington",
	470:  "Marcelo Richter da Silva",
	471:  "Jesper Darum",
	472:  "Sanjeev Kulkarni",
	473:  "John Stratford",
	474:  "Johann Frey",
	475:  "Alun Barnett",
	476:  "Davide Fabri",
	477:  "Ray Hallit",
	478:  "Dean Debaun",
	479:  "Robin Andersson",
	480:  "Tom Biehl",
	481:  "Kouji Mizusawa",
	482:  "Kantol Khek",
	483:  "Don Allen",
	484:  "Harry Skibbe",
	485:  "Gabriele Cavadini",
	486:  "Joakim Wiberg",
	487:  "Jack Tan Li Jun, Chief Executive Officer",
	488:  "Yin Kean Meng",
	489:  "Ulrich Pink",
	490:  "Patrick Adamo",
	491:  "Thomas Steuernagel",
	492:  "Makoto Fujinawa",
	493:  "Ing. T. Driessen",
	494:  "Ernst-Friedrich Althoff",
	495:  "Thierry Dubosse",
	496:  "Josef Pelc, Engineering Director",
	497:  "Bjarne Ibsen",
	498:  "Beom Ko",
	499:  "Gary Kruse",
	500:  "Nathaniel Crutcher",
	501:  "Michael Calmbach",
	502:  "Lim Chiat",
	503:  "Andrea Harrer",
	504:  "Illimar Soot",
	505:  "Jason Falbo",
	506:  "Ken Nickel",
	507:  "Mark Rawson",
	508:  "Chuck Clark",
	509:  "Masato Kuwana",
	510:  "Stefan Newbold",
	511:  "Robert Henig",
	512:  "Andreas Penzel",
	513:  "George Brunemann",
	514:  "Chris Childs",
	515:  "Jaehwan Joo",
	516:  "Shailendra Karody",
	517:  "Ryszard Dworzecki",
	518:  "Pawel Furtak",
	519:  "David Jones",
	520:  "Gunther Lawaczeck",
	521:  "Severin Koller",
	522:  "Roy Schofield",
	523:  "Hans-Roman Seifert",
	524:  "Ken Chigani",
	525:  "Bernat Garcia",
	526:  "Stipan Ruzicka",
	527:  "Brian Biboux",
	528:  "Adam Sterne",
	529:  "John Chisholm",
	530:  "Alf Katz",
	531:  "Peter Mc Shane",
	532:  "Johann Schuetzeneder",
	533:  "Conrad Stucki",
	534:  "A. Vardar",
	535:  "Peter Cobb",
	536:  "Nikola Jelic",
	537:  "Phil Houghton",
	538:  "Alexander Landgraf",
	539:  "Kiminori Tojima",
	540:  "Thomas Kwok",
	541:  "Hirakazu Tsukamoto",
	542:  "Zdenek Hanak, Jr.",
	543:  "Ray Wilson",
	544:  "Jie Yan",
	545:  "Michael Bell",
	546:  "Bjarne Jensen",
	547:  "Ernst Mack",
	548:  "Chuck O'Donnell",
	549:  "Toshihito Kon",
	550:  "Pan Qing",
	551:  "Terry Voigt",
	552:  "Richard Treffers",
	553:  "HoSung Yoo",
	554:  "Tony Pearce",
	556:  "Stephen Herzog",
	557:  "Marek Guzik",
	558:  "Vince Cisar",
	559:  "Travis Berry",
	560:  "Bruce Steigerwald",
	561:  "Rolf Schweizer",
	562:  "Toine Leerentveld",
	563:  "Fraser Eadie",
	564:  "Dejan Medan",
	565:  "Richard Travers",
	566:  "Andrew Blackmore",
	567:  "Lori Lee",
	568:  "Norman Hannotte",
	569:  "Dale Loia",
	570:  "David Hirst",
	571:  "Peter Ratkos",
	572:  "Erran Kagan",
	573:  "Jeong Uk Kim",
	574:  "Ken Lockhart",
	575:  "Andreas Krause",
	576:  "Robert Kline",
	577:  "Jochen Jagers",
	578:  "Man-Seung Yoo",
	579:  "Ireneusz Cicherski",
	580:  "Patrick McCormick",
	581:  "Jorn Albrektsen",
	582:  "Fabio Mauri",
	583:  "Karen Taylor",
	584:  "Ashutosh Vighne",
	585:  "Jason Nelson",
	586:  "Kevin Halloran",
	587:  "Rolf Eigenheer",
	588:  "Bernhard Leisch",
	589:  "Roberto Guazzoni",
	590:  "Ulderico Arcidiaco",
	591:  "Thomas Bernard",
	592:  "Richard Nidever",
	593:  "Simon Ki",
	594:  "Andre Keller",
	595:  "Wyvern Wang",
	596:  "Mai Zhao",
	597:  "YuChul Kim",
	598:  "Adrian Baumgartner",
	599:  "Nguyen Hoang Nam",
	600:  "Chuck Ridgeway",
	601:  "Giles Honeycutt",
	602:  "Jakub Bartkowiak",
	603:  "David John, International Sales Manager",
	604:  "Mark Bunting",
	605:  "Luca Marani",
	606:  "Klavs Kamuk",
	607:  "Mark Fisher",
	608:  "Markus Link",
	609:  "Dierk Astfalk",
	610:  "William Peters",
	611:  "Frank Pan",
	612:  "Jeremy Keen",
	613:  "Todd Sankey",
	614:  "Hirobumi Watanabe",
	615:  "Darren Legge",
	616:  "Jean-Marc Moscati",
	617:  "Jim Potter",
	618:  "Jonathan Trout",
	619:  "Rafal Stanuch",
	620:  "David Loyer",
	621:  "Ingar Pedersen",
	622:  "Jan Risen",
	623:  "Wolfgang Timelthaler",
	624:  "Benoit Lepeuple",
	625:  "Frank Lorenz",
	626:  "Stefan Ott",
	627:  "Stephan Trautvetter",
	628:  "Young Sik Kim",
	629:  "Liu Bing",
	630:  "Stefano Feltrin",
	631:  "Liang Wang",
	632:  "Chirag Nanavati",
	633:  "Jason Young",
	634:  "Kenji Saiki",
	635:  "Filip Zawadiak",
	636:  "Adem Erturk",
	637:  "Dan Hughes",
	638:  "Gary Clifford",
	639:  "Pierre Lefrancois",
	640:  "Dale McCarthy",
	641:  "Greg Ratzel, Manager, Software Engineering Group",
	642:  "Richard Gentry",
	643:  "Brian Puck",
	644:  "Johanna Wunsch",
	645:  "Robert Wills",
	646:  "Gordon Maretzki",
	647:  "Hirashiki Yasuhiro",
	648:  "Neal Meldrum",
	649:  "Marek Kolodziejczyk",
	650:  "Rich Cada",
	651:  "Jukka Hurtta",
	652:  "Petr Tomanek",
	653:  "Andreas Johnsson",
	654:  "Claire Hackman",
	655:  "Heinz Junkes",
	656:  "Marcus Mücke",
	657:  "Daniel Jackson",
	658:  "Leo Putz",
	659:  "Francis Beaudoin",
	660:  "Chang Ro Yoon",
	661:  "Mike Juhnke",
	662:  "Martin Schreiber",
	663:  "Slawomir Chelminski",
	664:  "Debbie Teng",
	665:  "David Flinchbaugh",
	667:  "Frederik Meerwaldt",
	668:  "Mitch Randall",
	669:  "Joakim Enerud",
	670:  "Marc Barbuti",
	671:  "Stephen McMahon",
	672:  "Claus Matthies",
	673:  "Tonello Fulvio",
	674:  "Thanh Chiem",
	675:  "Robert Newton",
	676:  "Eric Chang",
	677:  "Wil Moloughney",
	678:  "Roberto Di Tommaso",
	679:  "Shunji Aoki",
	680:  "Marcin Ploski",
	681:  "Mike Sussman",
	682:  "Vaclav Lukas",
	683:  "Wolfram Petritz",
	684:  "Alan McBride",
	685:  "YS Chen",
	686:  "Piotras Jenkinas",
	687:  "Bong Jin Lee",
	688:  "Lars Bo Hansen",
	689:  "Zeng Linchun",
	690:  "Anna Gagaczowska",
	691:  "Gregory Tropsa",
	692:  "Josiah Wiley",
	693:  "David Blyth",
	694:  "Kazuyoshi Nishiyama",
	695:  "Klaus Guetter",
	696:  "Randy Clayton",
	697:  "Christian Fortin",
	698:  "Zeng Yi",
	699:  "Michal Mysliwiec",
	700:  "Elki Iwabuchi",
	701:  "Steve Brown",
	702:  "Park Jun Hyun",
	703:  "Simon Baker",
	704:  "Mark Oellermann",
	705:  "Jeffrey Counts",
	706:  "Edwin Zijlstra",
	707:  "Andre Harel",
	708:  "Diego Contiero",
	709:  "Toshimitsu Nagayasu",
	710:  "Throstur Jonsson",
	711:  "Mike Giorgi",
	712:  "Gary Robbins",
	713:  "Rav Panchalingam",
	714:  "Inho Kim",
	715:  "Holger Liedermann",
	716:  "Adam Guzik",
	717:  "Matthias Sieber",
	718:  "Andre Wuest",
	719:  "Robert Dennelly",
	720:  "David Kniepkamp",
	721:  "Mahendra Ahir",
	722:  "Scott Rouse",
	723:  "Vijayendra Shamrao",
	724:  "K. Gurudath",
	725:  "Cuneyt Bektas",
	726:  "Miet Loix",
	727:  "Kamran Saleem",
	728:  "Leon Cao",
	729:  "Torbjorn Carlqvist",
	730:  "Zhang Jiwei",
	731:  "Stephen Dawson-Haggerty",
	732:  "Theodor Dotterweich",
	733:  "Nathaniel Frampton",
	734:  "Paul Brooker",
	735:  "Tim Doucette",
	736:  "Torsten Foels",
	737:  "Andreas Neuhaus",
	738:  "David Prevost",
	739:  "Chin Chao Yang",
	740:  "Michael Pfeffer",
	741:  "Ing. Zdenek Kolba",
	742:  "Mark Burdick",
	743:  "Ronald Kappeler",
	744:  "Jeffrey Mills",
	745:  "Benoit Jemine",
	746:  "Zhou Shihui",
	747:  "Stefan Thomanek",
	748:  "Bryan Powell",
	749:  "Torsten Schlaaff",
	750:  "Radoslaw Wicha",
	751:  "David Thompson",
	752:  "David Moore",
	753:  "Hendrik Baer",
	754:  "Sandeep Khanej",
	755:  "Marc Abdelahad",
	756:  "Mark Wagoner",
	757:  "Andreas Ascheneller",
	758:  "Pete Baselici",
	759:  "Brian Mottershead",
	760:  "Stephan Marnul",
	761:  "Chen Chong",
	762:  "Ruth Ward",
	763:  "Romano Manzoli",
	764:  "Stephen Love",
	765:  "Francesco Artusi",
	766:  "Howard Mills",
	767:  "Frank Fritz",
	768:  "Daniele Dalla Torre",
	769:  "Jim Christle",
	770:  "Hrvoje Sodan",
	771:  "Su Chao",
	772:  "Eric Roseman",
	773:  "Tomas Cizinsky",
	774:  "Jeffrey Davlyn",
	775:  "Paul Altimore",
	776:  "John Schmidt",
	778:  "Randy Glover",
	779:  "Rodrick Seely",
	780:  "William Zehler",
	781:  "Daryl Khoh",
	782:  "Wee Chong Yew",
	783:  "Petri Hakkarainen",
	784:  "Paolo Blem",
	785:  "David Dixon",
	786:  "Chandan Chowdhury",
	787:  "Frank Ableson",
	788:  "Gian Luca Ragazzini",
	789:  "Shawn Leimbrock",
	790:  "Hartmut Messerschmitt",
	791:  "Torben Foerster",
	792:  "Alex Greenspan",
	793:  "Roman Ruthofer",
	794:  "Dieter Schmitz",
	795:  "Jason Alvarez",
	796:  "Michael Picco",
	797:  "Murat Egrikavuk",
	798:  "Antoine Nabayaogo",
	799:  "David Wren",
	800:  "Mahesh Mudholkar",
	801:  "Oscar Deurloo",
	802:  "Joe Kimbrell",
	803:  "Julian Lamb",
	804:  "Rudolf Honegger",
	805:  "Brian Pham",
	806:  "Neil Robertson",
	807:  "Eric Pierce",
	808:  "Tobias Gentzell",
	809:  "Thomas Schmidt",
	810:  "Stan Lueck",
	811:  "Ben Hartman",
	812:  "Lance Stewart",
	813:  "Jason Bose",
	814:  "Michael Serafin",
	815:  "Dong Jianhua",
	816:  "Jerry Geis, Owner/President",
	817:  "Chao-Chou Hsiao",
	818:  "Lü Ming",
	819:  "Thomas Reimann",
	820:  "Alan Tschirner",
	821:  "Dave Davis",
	822:  "Paul Korzycki",
	823:  "Chris Frankel",
	824:  "Tommi Mäkelä",
	825:  "Daniel Niewirowicz",
	826:  "Tomasz Bal",
	827:  "Mark Chang",
	828:  "Ricardo Galnares",
	829:  "Ajay Singh",
	830:  "Tom John",
	831:  "Joao Dias",
	832:  "Stuart Allen",
	833:  "Harald Stoerk",
	834:  "Jeff Scilingo",
	835:  "Gabriel Mihaila",
	836:  "Clark Gunness",
	837:  "Stefan Hauck",
	838:  "Nicholas Jones",
	839:  "Andrea Ferrarelli",
	840:  "Zhang Yaoxiang",
	841:  "Artur Miller",
	842:  "Christian Tremblay",
	843:  "Thomas Reif",
	844:  "Lin Cheng",
	845:  "Joachim Schullerer",
	846:  "Piotr Pelka",
	847:  "Urs Hirt",
	848:  "Pawel Ropiak",
	849:  "Miroslaw Kot",
	850:  "Thomas Irming",
	851:  "Sebastian Martin",
	852:  "Geoff Archenhold",
	853:  "Guo Qihui",
	854:  "Dave Schiopucie",
	855:  "Todd Rossi",
	856:  "Muzaffer Kazakoglu",
	857:  "Mark Matyac",
	858:  "Martin Croome",
	859:  "Robin Hohl",
	860:  "Christian Kurz",
	861:  "Fabin Zhong",
	862:  "Zhou Mi",
	863:  "Andres Tavil",
	864:  "Jeff Hoogveld",
	865:  "Joel Haggar",
	866:  "Harold Jepsen",
	867:  "Ubayathulla Ahamed",
	868:  "Henry Chang",
	869:  "",
	870:  "Robert Noble",
	871:  "Stanley Toh",
	872:  "Leen Geebelen",
	873:  "Brett Austin",
	874:  "Simon Justyn",
	875:  "Paul Bieganski",
	876:  "Richard McElhinney",
	877:  "Henrik Plueth",
	878:  "Nathan Sacks",
	879:  "Lukas Dillier",
	880:  "Anu Katka",
	881:  "Eike Weiss",
	882:  "Thomas Chiu",
	883:  "Terry Sprangers",
	884:  "Mike Sharkey",
	885:  "Bill Kuhns",
	886:  "Heather Granneman",
	887:  "Friedrich Brück",
	889:  "Zsolt Banko",
	890:  "James Rhodes",
	891:  "Dusko Lukanic-Simpson",
	892:  "Frédéric Hess",
	893:  "Sudhir Pendse",
	894:  "Doug Harp",
	895:  "Lee Hocheol",
	896:  "Masataka Sugano",
	897:  "Paul Schroeter",
	898:  "Antoni Gates",
	899:  "Bernhard Wiedemann",
	900:  "David Elliott",
	901:  "Florian Morris",
	902:  "Shari Parillo",
	903:  "Jussi Rantanen",
	904:  "Thomas Hain",
	905:  "Andrew Bishop",
	906:  "K. Rajasekaran",
	907:  "Jack Lee",
	908:  "Apurba Pradhan",
	909:  "Warren Beacom",
	910:  "Janne Pehkonen",
	911:  "",
	912:  "Jason Burt",
	913:  "Pingzhong Li",
	914:  "Nicole Wenzel",
	915:  "Markus Jabs",
	916:  "Christof De Backere",
	917:  "Colin Cullinan",
	918:  "Paul Kearney",
	919:  "Derek Cowburn",
	920:  "Louis-Philippe Rose",
	921:  "Jeff Hendrickson",
	922:  "Alessio Di Gioia",
	923:  "Tomonari Hiraizumi",
	924:  "Tom Gordon",
	925:  "Ela Sibilska",
	926:  "Jean-Christophe Carette",
	927:  "Dirk Brinkmann",
	928:  "Chris Starta",
	929:  "Eduardo Ricalde",
	930:  "Peter Kalt",
	931:  "Erik Maseng",
	932:  "Ludwig De Locht",
	933:  "Andrius Tamasauskis",
	934:  "Klaus Lorenz",
	935:  "Hermann Lertes",
	936:  "Shaun Fitzgerald",
	937:  "Pierre Crokaert",
	938:  "Tiziano Guidetti",
	939:  "Erich Weber",
	940:  "Alan Davis",
	941:  "Jaimie Crafton",
	942:  "James Spruell",
	943:  "Tian Qi",
	944:  "MC Randelhoff",
	945:  "Filip Dudek",
	946:  "Ingo Brauns",
	947:  "Kohei Chimura",
	948:  "Benjamin Frei",
	949:  "James Sun",
	950:  "BeiShan Li",
	951:  "Robert Wallace",
	952:  "Peter Rockett",
	953:  "Steve Fallon",
	954:  "Denis Badoil",
	955:  "Trevor Creary",
	956:  "Matt Nowak",
	957:  "Sandy Klivans",
	958:  "Arifa Riaz",
	959:  "Patrick Tabouret",
	960:  "Jason McGehee",
	961:  "John Sondericker III",
	962:  "Jose Beltran",
	963:  "Geert Hoevenaars",
	964:  "Jack Neyer",
	965:  "Pradit Kaewart",
	966:  "Tom Randall",
	967:  "Boris Napernikov",
	968:  "Daniel Zotti",
	969:  "Seungman Lee",
	970:  "Honggang Fu",
	971:  "Kihwan Cho",
	972:  "Khoi Nguyen",
	973:  "Lars Elling",
	974:  "Brad Lonergan",
	975:  "Chris Bao",
	976:  "Robert Merki",
	977:  "Juan Garcia",
	978:  "Michael Press",
	979:  "Yong Hao",
	980:  "Christopher Adam",
	981:  "Andrew French",
	982:  "Larry Cheng",
	983:  "Vincent D'Amore",
	984:  "Jean-Christophe Almira",
	985:  "Ruben Kollmar",
	986:  "Bernat Pons-Estel",
	987:  "Daniel Ronald",
	988:  "Pieter De Clerck",
	989:  "Wayne Barkley",
	990:  "Su Bensheng",
	991:  "Roy Harvey",
	992:  "Tom Haskell",
	993:  "Mike Harris",
	994:  "Shamsul Zainudin",
	995:  "Steve Payne",
	996:  "Tyler Bessette",
	997:  "Jim Dewar",
	998:  "Klaus Vamberszky",
	1000: "Weidacher Hartwig",
	1001: "Dave Rios",
	1002: "Allan Organ",
	1003: "German Akselrod",
	1004: "Nigel Smith",
	1005: "Peter Yang",
	1006: "Edvardas Liakas",
	1007: "Jarno Mitjonen",
	1008: "Mark Eldridge",
	1009: "Michael Farnon",
	1010: "Robert Green",
	1011: "Douglas Ritchie",
	1012: "Ryan Beggs",
	1013: "Mark Nathan",
	1014: "Romuald Kliukovskij",
	1015: "Michel Bergeron",
	1016: "Richard Long",
	1017: "Raheel Chaudhry",
	1018: "Gunther Haslauer",
	1019: "Robert Haidinger",
	1020: "Timothy Davis",
	1021: "Rene Rieck",
	1022: "Don Kasper",
	1023: "Chris Smith",
	1024: "Philip Harman",
	1025: "Andy Ryan",
	1026: "Matt James-Wallace",
	1027: "Anthony Stufano",
	1028: "Matti Hatonen",
	1029: "Silvano Maffessoli",
	1030: "Daisuke Fujimoto",
	1031: "M. Lütkemann",
	1032: "Daniel Mousseau",
	1033: "Sanjib Baral",
	1034: "Etienne-Vincent Hardy",
	1035: "Bill Kubsh",
	1036: "Scott Henson",
	1037: "Tobias Klein",
	1038: "Darlusz Tront",
	1039: "Greg Highfill",
	1040: "Claudio Caldera",
	1041: "John Carrieri",
	1042: "Thomas Schmuck",
	1043: "Mark Hodge",
	1044: "Audrius Janusauskas",
	1045: "Michel Seiler",
	1046: "Bruce Schult",
	1047: "Matthew James",
	1048: "Daniel Noiseux",
	1049: "Stephan Eisler",
	1050: "Darrel O'Pry",
	1051: "Bernard Saint-Yves",
	1052: "Sven Gebhardt",
	1053: "Maofan Hsu",
	1054: "Quirino Nardin",
	1055: "David Tesluk",
	1056: "John Montgomery",
	1057: "Mark Pantazes",
	1058: "Brian Smith",
	1059: "Casey Jon McKay",
	1060: "Keya Joshi",
	1061: "Michal Pasula",
	1062: "Rafael Mardones",
	1063: "Satoshi Osawa",
	1064: "Per Martenson",
	1065: "Roland Unger",
	1066: "Ken Takeda",
	1067: "Antonio Garcia",
	1068: "Steven Morgan",
	1069: "Jeffrey Stoltenow",
	1070: "Michael Grant",
	1071: "Miroslav Crv",
	1072: "Mark Poulsen",
	1073: "Baden Hughes",
	1074: "Johannes Auer",
	1075: "Rogerio Zanotta",
	1076: "Muhammad Sadqain",
	1077: "Patrick Isenschmid",
	1078: "Tomáš Hora",
	1079: "Laurent Laparra",
	1080: "Martin Chlupáč",
	1081: "David Eves",
	1082: "Jason White",
	1083: "James Galm",
	1084: "Jan Hřebec",
	1085: "Javier Lomas",
	1086: "Robert Jarzabek",
	1087: "Christopher Kelly",
	1088: "Steven Song",
	1089: "Randy Roy",
	1090: "Andrew Green",
	1091: "Tom Podgurski",
	1092: "Aleksander Kruszewicz",
	1093: "Mark Jarman",
	1094: "Paul Calton",
	1095: "Wenping Ren",
	1096: "Shian Li",
	1097: "Lim Soon-Keat",
	1098: "Derek Noffke",
	1099: "Eric Van Zant",
	1100: "KC Tsui",
	1101: "Eric Zweighaft",
	1102: "Wang YangYang",
	1103: "Thomas Stengl",
}

var vendorIDAddress = map[VendorID]string{}
